version: "3"

volumes:
  llmchat-db-docker:
    external: true
services:
  ui:
    hostname: ui
    build:
      context: .
      dockerfile: apps/ui/Dockerfile
    image: "askme/ui"
    container_name: "ui"
    ports:
      - "80:80"
    restart: unless-stopped
  api:
    hostname: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    image: "askme/api"
    container_name: "api"
    environment:
      OLLAMA_HOST: "llmchat"
      OLLAMA_PORT: "11434"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "llmchat"
      POSTGRES_USER: "locallm"
      POSTGRES_PASSWORD: "locallm"
    ports:
      - "3000:3000"
    restart: unless-stopped
  postgres:
    hostname: postgres
    build:
      context: .
      dockerfile: apps/pgvector/Dockerfile
    image: "llmchat-db"
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA_PATH}
    volumes:
      - ${POSTGRES_VOLUMES}
    ports:
      - "5432:5432"
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ${OLLAMA_VOLUME_1}
      - ${OLLAMA_VOLUME_2}
    container_name: ollama
    tty: true
    restart: always
